name: build

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'
  pull_request:
    branches:
      - 'main'
    types: [opened, synchronize]
  pull_request_target:
    branches:
      - 'main'
    types: [labeled]
  workflow_dispatch:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    if: >
      ${{
        github.event_name == 'pull_request' ||
        (github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name, 'safe to test')) ||
        startsWith(github.ref, 'refs/tags/')
      }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
#      - name: lint
#        run: ./gradlew spotlessCheck
#      - name: Test
#        run: ./gradlew test
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    needs: [ test ]
    if: ${{ github.event_name == 'workflow_dispatch' || contains(github.ref, 'refs/tags/') }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: gem
        run: ./gradlew gem
      - name: push gem(embulk-input-mysql)
        uses: trocco-io/push-gem-to-gpr-action@v1
        with:
          language: java
          gem-path: "./embulk-input-mysql/build/gems/*.gem"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
